# http://travis-ci.org/#!/jupyter/jupyter_core
language: python
sudo: false
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install -f travis-wheels/wheelhouse -r dev-requirements.txt .
script:
    - py.test jupyter_core
