# http://travis-ci.org/#!/jupyter/jupyter_core
language: python
python:
  - nightly
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
before_install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
install:
  - pip install -r dev-requirements.txt .
script:
  - py.test jupyter_core
matrix:
  allow_failures:
    - python: nightly
