# http://travis-ci.org/#!/jupyter/jupyter_core
language: python
sudo: false
python:
  - nightly
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7
before_install:
  - pip install --upgrade setuptools pip
install:
  - pip install -r dev-requirements.txt .
script:
  - py.test jupyter_core
